- labelCloud/utils/oglhelper.py
- labelCloud/view/viewer.py
Problem: Cursor was off by fixed distance for retina displays due to wrong coordinate calculation of `GLU.unproject()`
Solution: Consider `display pixel ratio` when calculating coordinates from screen coordinates.
Closes #7
> Fix coordinate problem for retina displays

- labelCloud/app.py
- labelCloud/view/gui.py
The labelCloud UI looks very different on MacOS compared to Linux.
- Fix this issue by enforcing a generic design.
- Fix the disappearance of ticks in the menu bar by forbidding native menu bars
> Fix mac style

- .github/workflows/unit-tests.yml
- config.ini
- docs/documentation.md
- labelCloud/ressources/default_config.ini
- labelCloud/view/viewer.py
- tests/integration/conftest.py
- tests/unit/conftest.py
- increase OpenGL clipping space (0.1 - 300)
- add near and far plane to config
- add ignore rules to flake
Closes: #16
> Change clipping space and add to config.ini

- labelCloud/control/pcd_manager.py
Hi Christoph,
Thanks for putting this tool together - great work!
For my project, I'm working with large pointclouds, e.g.:
> Point Cloud Center:		[  5.33   9.52 498.09]
> Point Cloud Minimums:	[-218.82 -310.2   484.31]
> Point Cloud Maximums:	[278.17 312.32 534.99]
The previous trans_init computation didn't quite work for this use case - here is a simpler and more robust one I believe.
> simpler initial viewpoint computation

- labelCloud/control/pcd_manager.py
- do not attempt to save a perspective without a point cloud beeing loaded
Relates: #31
> Fix save perspective

- labelCloud/control/bbox_controller.py
- labelCloud/control/controller.py
- labelCloud/control/drawing_manager.py
- labelCloud/control/label_manager.py
- labelCloud/label_formats/__init__.py
- labelCloud/label_formats/base.py
- labelCloud/label_formats/centroid_format.py
- labelCloud/label_formats/kitti_format.py
- labelCloud/label_formats/vertices_format.py
- labelCloud/labeling_strategies/__init__.py
- labelCloud/labeling_strategies/base.py
- labelCloud/labeling_strategies/picking.py
- labelCloud/labeling_strategies/spanning.py
- labelCloud/model/__init__.py
- labelCloud/view/gui.py
- labelCloud/view/viewer.py
- add `label_formats` module
- add `labeling_strategies` module
- add script for each class
- use classmethods
> Add modules to improve structure

- labelCloud/control/pcd_manager.py
- take minimum of diagonal and 90% far_plane
- assume that there are at least some points from the center visible
Closes: #39
Relates: #36
> Limit initial zoom to far_plane

- README.md
- labelCloud/control/label_manager.py
- labelCloud/label_formats/kitti_format.py
- tests/unit/test_label_export.py
- tests/unit/test_label_import.py
- transform the position, dimension and rotation of KITTI labels before
loading or saving
- add kitti_untransformed for backward compatibility
Thanks to @sondisonda for finding the correct transformation.
Closes: #35
> Add necessary transformation to KITTI

- .gitignore
- config.ini
- labelCloud/control/pcd_manager.py
- labelCloud/model/point_cloud.py
- labelCloud/resources/interfaces/interface.ui
- labelCloud/tests/unit/test_color.py
- labelCloud/utils/color.py
- labelCloud/view/gui.py
- labelCloud/view/viewer.py
- requirements.txt
- setup.cfg
This PR introduces the functionality of blending point colors with label colors, which generated automatically based on a helper function.
Specifically,
1. Three more config options and UI changes:
- `MODE.segmentation` (bool): whether or not to read segmentation labels and enable the blending effect
- `POINTCLOUD.color_with_label` (bool): whether or not to blend the point colors with label colors, this is also made configurable/ changable in the GUI.
- `POINTCLOUD.label_color_mix_ratio`: final_color = ratio * label_color + (1-ratio) * rgb_color
2. Change the vertex buffer from 1 to 3:
- 3 buffers for XYZ, original RGB and blended RGB
- change the `PointCloud.draw_pointcloud` so it's changed the point colors according to `POINTCLOUD.color_with_label`
- rename and make it part of …
> Blend point colors with labels

- labelCloud/tests/integration/test_gui.py
- labelCloud/tests/integration/test_labeling.py
- adapt integration tests to changed namings
Relates: #93
Forgot to also apply the renamed attributes to the integration. Unfortunately the integration tests stopped working in the Github pipeline some months ago. I assume Github changes sth. in the container setup.
> Fix integration tests

- .gitignore
- config.ini
- docs/documentation.md
- labelCloud/control/bbox_controller.py
- labelCloud/control/pcd_manager.py
- labelCloud/io/__init__.py
- labelCloud/io/pointclouds/open3d.py
- labelCloud/io/segmentations/base.py
- labelCloud/io/segmentations/numpy.py
- labelCloud/model/point_cloud.py
- labelCloud/resources/default_config.ini
- labelCloud/resources/interfaces/interface.ui
- labelCloud/tests/unit/segmentation_handler/test_numpy_segmentation_handler.py
- labelCloud/utils/color.py
- labelCloud/view/gui.py
- labelCloud/view/settings_dialog.py
- labels/schema/label_definition.json
- labels/segmentation/schema/label_definition.json
- requirements.txt
My original plan was to put this together with the PR that assigning box labels to point labels but I realise that it's a logically separated functionality, so I split it to this PR so it's easier to review component-by-component.
This PR replace the class edit box to class drop down box to force the user to have a restricted set of options when setting the box classes as well as the point classes. Because of the nature of it, the class definition in `config.ini` is removed. Ideally, `std_object_class` should be removed as well but because there is another [PR](https://github.com/ch-sa/labelCloud/pull/94) addressing that, it is retained for now.
The label_definition concept is therefore shared across two modes. This also paves the way for the label definition `setup` idea. 
Expected …
> Use dropdown list instead of editbox for box classes

- config.ini
- docs/configuration.md
- labelCloud/control/controller.py
- labelCloud/control/label_manager.py
- labelCloud/control/pcd_manager.py
- labelCloud/definitions/__init__.py
- labelCloud/definitions/colors.py
- labelCloud/definitions/types.py
- labelCloud/io/labels/base.py
- labelCloud/io/labels/config.py
- labelCloud/io/segmentations/base.py
- labelCloud/model/bbox.py
- labelCloud/model/point_cloud.py
- labelCloud/resources/default_config.ini
- labelCloud/tests/unit/segmentation_handler/test_numpy_segmentation_handler.py
- labelCloud/utils/color.py
- labelCloud/utils/oglhelper.py
- labelCloud/view/gui.py
- labelCloud/view/settings_dialog.py
- labels/_classes.json
Hi @chingyulin,
unfortunately I cannot put you as reviewer but I would like to get your opinion on this idea:
I thought it makes sense to have the label definitions/ schema in an extra single file as you suggested.
This makes also sense for the object detection use case as label schemas are mostly project specific and thus should be located close to the labels. Also it would be a cool feature to have label colors for object detection.
So what I did is adding more data to the schema file and name + place it more generic so it fits both cases.
What do you think of this idea? (This is just a draft, I would continue with the implement then ...)
Changes:
- use structure with all details
- includes id, color and default flag
- could be autogenerated and partly optional
- would be reusable for …
> Proposal for class definitions

- labelCloud/control/label_manager.py
- labelCloud/io/labels/config.py
- labelCloud/tests/integration/conftest.py
- labelCloud/utils/color.py
- labels/schema/label_definition.json
This ensures backwards compatibility with old labelCloud versions and the label files that were generated with those.
Additionally this helps if the `_classes.json` was accidentally deleted.
> Add unknown label classes from loaded labels

- config.ini
- docs/configuration.md
- docs/index.md
- labelCloud/control/controller.py
- labelCloud/resources/interfaces/interface.ui
- labelCloud/resources/interfaces/settings_interface.ui
- labelCloud/view/gui.py
- labelCloud/view/settings_dialog.py
- add a feature to carry over labels to the next point cloud
- can be activated via config and menu action
- will only copy labels if the next point cloud has no bounding boxes so far
Closes: #120
> Add label propagation

- labelCloud/view/gui.py
- label_list is focused on label switch
- events were then not considered in event filter
Closes: #132
> Add label_list to event filter

- labelCloud/control/controller.py
- labelCloud/io/labels/config.py
- labelCloud/io/labels/exceptions.py
- labelCloud/model/point_cloud.py
- labelCloud/view/gui.py
- labelCloud/view/startup_dialog.py
**This PR addresses**:
- mismatch between segmentation labels and label definition. It prompts a message box to user to overwrite the missing labels with the default labels, if not the label stays as-is. The check happens when a PointCloud is initialised or is being saved to .bin file https://github.com/ch-sa/labelCloud/issues/124
- validate the self-correctness of the data in the StartupDialog and prompts a message box when errors occurred. Handled errors are 1. no label defined, 2. label ids are not unique, 3. label name is empty, 4. default id in the _classes.json doesn't present in the dialog. The trackback of the non-handled errors are printed to the message box.
**Screenshots of the error handling in the StartupDialog**
No label defined
default id in the _classes.json doesn't …
> Validate the data in StartupDialog and handle mismatched segmentation labels

- config.ini
- labelCloud/io/labels/kitti.py
- labelCloud/resources/default_config.ini
I assumed that `calib` folder is located next to `labels`.
> Fixed import of KITTI labels via calibration files

- labelCloud.py
- labelCloud/control/controller.py
- labelCloud/control/pcd_manager.py
- labelCloud/io/labels/kitti.py
- labelCloud/model/bbox.py
- labelCloud/model/point_cloud.py
- labelCloud/tests/integration/conftest.py
- labelCloud/tests/unit/segmentation_handler/test_numpy_segmentation_handler.py
- labelCloud/view/gui.py
- labelCloud/view/viewer.py
- requirements.txt
This PR implements a functionality to crop the point cloud inside a box and save as a separate bounding box. It reuses the menu of the boxes. A feature request here: https://github.com/ch-sa/labelCloud/issues/27
> Crop the points inside a box and save as as a separate point cloud

- labelCloud/__main__.py
I was having trouble running labelCloud on Windows. Passing floats to a Qt function where it expected integers crashed the program. I'll include the error message if I can find the time to reproduce, but here's the patch for now.
> Fix issue with GUI not accepting floats.

- .github/workflows/unit-tests.yml
- requirements.txt
- force older PyOpenGL version
Relates: #145
> Fix testing pipeline

- README.md
- labelCloud/control/controller.py
- labelCloud/io/labels/config.py
In this PR I implemented some workflow improvements stated in #143:
- First bbox autoselection on sample change
- New hotkeys for sample/bbox/class switch
- Updated list of hotkeys in README.md
A bit of reasoning under new hotkeys:
During labeling I noticed, that I use the program in two modes:
1. Labeling sequential dataset
2. Fixing incorrect labeling
In (1) I have left hand on keyboard and right on mouse, so I need all keys be accesible with one hand (all keys should be near `WASD`).
In (2) case I don't need mouse and can use keyboard only (arrows to navigate dataset with right hand and free left hand to fix errors).
> New hotkeys and bbox autoselection

- labelCloud/io/labels/kitti.py
- labelCloud/tests/integration/test_gui.py
- labelCloud/tests/unit/test_label_import.py
- previous logic for `kitti_untransformed` format did not follow the specification
https://github.com/bostondiditeam/kitti/blob/master/resources/devkit_object/readme.txt#L59
- inverses the dimension sequence to height, width, length
> Ch sa/fix kitti dimensions

- README.md
- docs/shortcuts.md
- labelCloud/control/alignmode.py
- labelCloud/control/bbox_controller.py
- labelCloud/control/config_manager.py
- labelCloud/control/controller.py
- labelCloud/control/pcd_manager.py
- labelCloud/model/point_cloud.py
- labelCloud/utils/oglhelper.py
- requirements.txt
This PR adds keyboard shortcuts for increasing/decreasing bbox scale (length, width, height).
I extended the documentation to reflect this change.
It also includes a small change to load pointcloud files recursively.
> Add keyboard shortcuts for scaling, allow loading files recursively

- labelCloud/io/labels/kitti.py
> Use height to calculate kitti centroid
